services:
  backend-sqlite:
    container_name: backend-sqlite
    build:
      context:      /home/oseivane/Transcendence/srcs/containers/backend-sqlite
    env_file:       .env
    restart:        always
      
    networks:       [transcendence]
    depends_on:     [node]
    volumes:        [backend-sqlite-data:/var/www/html]

  blockchain:
    container_name: blockchain
    build:
      context:      ./containers/blockchain
    env_file:       .env
    restart:        always
      
    networks:       [transcendence]
    depends_on:     [backend-sqlite]
    volumes:        [blockchain-data:/var/www/html]

  frontend:
    container_name: frontend
    build:
      context:      ./containers/frontend
    env_file:       .env
    restart:        always
    ports:          [3000:3000] 
    networks:       [transcendence]
    depends_on:     [waf]
    volumes:        [frontend-data:/app]

  node:
    container_name: node
    build:
      context:      ./containers/node
    env_file:       .env
    restart:        always
    ports:
      - "4000:4000" 
    networks:       [transcendence]
    depends_on:     [frontend]
    volumes:        
      - ./containers/node:/app

  waf:
    container_name: waf
    build:
      context:      ./containers/waf
    env_file:       .env
    restart:        on-failure

    ports:          [443:443]
    networks:       [transcendence]


volumes:
  backend-sqlite-data:
    driver:         local
    driver_opts:
      type:         none
      device:       /home/oseivane/Transcendence/srcs/volumes/backend-sqlite
      o:            bind

  blockchain-data:
    driver:         local
    driver_opts:
      type:         none
      device:       ./volumes/blockchain
      o:            bind

  frontend-data:
    driver:         local
    driver_opts:
      type:         none
      device:       ./volumes/frontend
      o:            bind

  node-data:
    driver:         local
    driver_opts:
      type:         none
      device:       ./volumes/node
      o:            bind


networks:
  transcendence:
    driver: bridge