services:
  backend-sqlite:
    container_name: backend-sqlite
    build:
      context:      ./containers/backend-sqlite
    env_file:       .env
    restart:        always
      
    networks:       [transcendence]
<<<<<<< HEAD
    depends_on:     [node_js]
=======
    depends_on:     [node]
>>>>>>> c18e4ade4191a53c0e2ba3d8e3d050308fe75a3c
    volumes:        [backend-sqlite-data:/var/www/html]

  blockchain:
    container_name: blockchain
    build:
      context:      ./containers/blockchain
    env_file:       .env
    restart:        always
      
    networks:       [transcendence]
    depends_on:     [backend-sqlite]
    volumes:        [blockchain-data:/var/www/html]

  frontend:
    container_name: frontend
    build:
      context:      ./containers/frontend
    env_file:       .env
    restart:        always
      
    networks:       [transcendence]
    depends_on:     [waf]
<<<<<<< HEAD
    volumes:        [frontend-data:/var/www/html]

  node_js:
    container_name: node_js
    build:
      context:      ./containers/node_js
=======
    volumes:        [frontend-data:/app]

  node:
    container_name: node
    build:
      context:      ./containers/node
>>>>>>> c18e4ade4191a53c0e2ba3d8e3d050308fe75a3c
    env_file:       .env
    restart:        always
      
    networks:       [transcendence]
    depends_on:     [frontend]
<<<<<<< HEAD
    volumes:        [node_js-data:/var/www/html]
=======
    volumes:        [node-data:/app]
>>>>>>> c18e4ade4191a53c0e2ba3d8e3d050308fe75a3c

  waf:
    container_name: waf
    build:
      context:      ./containers/waf
    env_file:       .env
    restart:        on-failure

    ports:          [443:443]
    networks:       [transcendence]
<<<<<<< HEAD
    volumes:        [waf-data:/var/www/html]
=======
>>>>>>> c18e4ade4191a53c0e2ba3d8e3d050308fe75a3c


volumes:
  backend-sqlite-data:
    driver:         local
    driver_opts:
      type:         none
      device:       ./volumes/backend-sqlite
      o:            bind

  blockchain-data:
    driver:         local
    driver_opts:
      type:         none
      device:       ./volumes/blockchain
      o:            bind

  frontend-data:
    driver:         local
    driver_opts:
      type:         none
      device:       ./volumes/frontend
      o:            bind

<<<<<<< HEAD
  node_js-data:
    driver:         local
    driver_opts:
      type:         none
      device:       ./volumes/node.js
      o:            bind

  waf-data:
    driver:         local
    driver_opts:
      type:         none
      device:       ./volumes/waf
=======
  node-data:
    driver:         local
    driver_opts:
      type:         none
      device:       ./volumes/node
>>>>>>> c18e4ade4191a53c0e2ba3d8e3d050308fe75a3c
      o:            bind


networks:
  transcendence:
    driver: bridge